-- MySQL Script generated by MySQL Workbench
-- qui 21 fev 2019 16:59:15 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_imobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_imobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_imobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `bd_imobiliaria` ;

-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`profissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`profissoes` (
  `id_prof` INT(22) NOT NULL AUTO_INCREMENT,
  `nome_prof` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_prof`))
ENGINE = InnoDB
AUTO_INCREMENT = 772
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`tipo_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`tipo_endereco` (
  `id_tipo_endereco` INT NOT NULL AUTO_INCREMENT,
  `tipo_endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `num` VARCHAR(45) NOT NULL,
  `tipo_endereco_id_tipo_endereco` INT NOT NULL,
  PRIMARY KEY (`id_endereco`, `tipo_endereco_id_tipo_endereco`),
  INDEX `fk_endereco_tipo_endereco1_idx` (`tipo_endereco_id_tipo_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_tipo_endereco1`
    FOREIGN KEY (`tipo_endereco_id_tipo_endereco`)
    REFERENCES `bd_imobiliaria`.`tipo_endereco` (`id_tipo_endereco`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`Regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`Regiao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`Estado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodigoUf` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Uf` CHAR(2) NOT NULL,
  `Regiao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Regiao_Id`),
  INDEX `fk_Estado_Regiao1_idx` (`Regiao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Regiao1`
    FOREIGN KEY (`Regiao_Id`)
    REFERENCES `bd_imobiliaria`.`Regiao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`Municipio` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Estado_Id` INT NOT NULL,
  `Estado_Regiao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Estado_Id`, `Estado_Regiao_Id`),
  INDEX `fk_Municipio_Estado1_idx` (`Estado_Id` ASC, `Estado_Regiao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Municipio_Estado1`
    FOREIGN KEY (`Estado_Id` , `Estado_Regiao_Id`)
    REFERENCES `bd_imobiliaria`.`Estado` (`Id` , `Regiao_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`contato` (
  `id contato` INT NOT NULL AUTO_INCREMENT,
  `contato` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT '						',
  `sobrenome` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `profissoes_id_prof` INT(22) NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `endereco_tipo_endereco_id_tipo_endereco` INT NOT NULL,
  `Municipio_Id` INT NOT NULL,
  `Municipio_Estado_Id` INT NOT NULL,
  `Municipio_Estado_Regiao_Id` INT NOT NULL,
  `contato_id contato` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `profissoes_id_prof`, `endereco_id_endereco`, `endereco_tipo_endereco_id_tipo_endereco`, `Municipio_Id`, `Municipio_Estado_Id`, `Municipio_Estado_Regiao_Id`, `contato_id contato`),
  INDEX `fk_pessoa_profissoes1_idx` (`profissoes_id_prof` ASC) VISIBLE,
  INDEX `fk_pessoa_endereco1_idx` (`endereco_id_endereco` ASC, `endereco_tipo_endereco_id_tipo_endereco` ASC) VISIBLE,
  INDEX `fk_pessoa_Municipio1_idx` (`Municipio_Id` ASC, `Municipio_Estado_Id` ASC, `Municipio_Estado_Regiao_Id` ASC) VISIBLE,
  INDEX `fk_pessoa_contato1_idx` (`contato_id contato` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_profissoes1`
    FOREIGN KEY (`profissoes_id_prof`)
    REFERENCES `bd_imobiliaria`.`profissoes` (`id_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_endereco1`
    FOREIGN KEY (`endereco_id_endereco` , `endereco_tipo_endereco_id_tipo_endereco`)
    REFERENCES `bd_imobiliaria`.`endereco` (`id_endereco` , `tipo_endereco_id_tipo_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_Municipio1`
    FOREIGN KEY (`Municipio_Id` , `Municipio_Estado_Id` , `Municipio_Estado_Regiao_Id`)
    REFERENCES `bd_imobiliaria`.`Municipio` (`Id` , `Estado_Id` , `Estado_Regiao_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_contato1`
    FOREIGN KEY (`contato_id contato`)
    REFERENCES `bd_imobiliaria`.`contato` (`id contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`contrutora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`contrutora` (
  `id_contrutora` INT NOT NULL AUTO_INCREMENT,
  `nome_const` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contrutora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`finalidade_busca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`finalidade_busca` (
  `idfinalidade_busca` INT NOT NULL AUTO_INCREMENT,
  `desc_finalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfinalidade_busca`))
ENGINE = InnoDB
COMMENT = 'moradia, investimento,negocios,outros\n';


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`tipo_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`tipo_imovel` (
  `id_tipo_imovel` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(45) NOT NULL,
  `contrutora_id_contrutora` INT NOT NULL,
  `finalidade_busca_idfinalidade_busca` INT NOT NULL,
  PRIMARY KEY (`id_tipo_imovel`, `contrutora_id_contrutora`, `finalidade_busca_idfinalidade_busca`),
  INDEX `fk_tipo_imovel_contrutora1_idx` (`contrutora_id_contrutora` ASC) VISIBLE,
  INDEX `fk_tipo_imovel_finalidade_busca1_idx` (`finalidade_busca_idfinalidade_busca` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_imovel_contrutora1`
    FOREIGN KEY (`contrutora_id_contrutora`)
    REFERENCES `bd_imobiliaria`.`contrutora` (`id_contrutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_imovel_finalidade_busca1`
    FOREIGN KEY (`finalidade_busca_idfinalidade_busca`)
    REFERENCES `bd_imobiliaria`.`finalidade_busca` (`idfinalidade_busca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`condicao_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`condicao_imovel` (
  `id_condicao_imovel` INT NOT NULL AUTO_INCREMENT,
  `desc_cond_imovel` VARCHAR(45) NOT NULL,
  `tipo_imovel_id_tipo_imovel` INT NOT NULL,
  `tipo_imovel_contrutora_id_contrutora` INT NOT NULL,
  `tipo_imovel_finalidade_busca_idfinalidade_busca` INT NOT NULL,
  PRIMARY KEY (`id_condicao_imovel`, `tipo_imovel_id_tipo_imovel`, `tipo_imovel_contrutora_id_contrutora`, `tipo_imovel_finalidade_busca_idfinalidade_busca`),
  INDEX `fk_condicao_imovel_tipo_imovel1_idx` (`tipo_imovel_id_tipo_imovel` ASC, `tipo_imovel_contrutora_id_contrutora` ASC, `tipo_imovel_finalidade_busca_idfinalidade_busca` ASC) VISIBLE,
  CONSTRAINT `fk_condicao_imovel_tipo_imovel1`
    FOREIGN KEY (`tipo_imovel_id_tipo_imovel` , `tipo_imovel_contrutora_id_contrutora` , `tipo_imovel_finalidade_busca_idfinalidade_busca`)
    REFERENCES `bd_imobiliaria`.`tipo_imovel` (`id_tipo_imovel` , `contrutora_id_contrutora` , `finalidade_busca_idfinalidade_busca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`situaçao_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`situaçao_imovel` (
  `id_situaçao_imovel` INT NOT NULL AUTO_INCREMENT,
  `desc_sit_imovel` VARCHAR(45) NOT NULL,
  `tipo_imovel_id_tipo_imovel` INT NOT NULL,
  `tipo_imovel_contrutora_id_contrutora` INT NOT NULL,
  `tipo_imovel_finalidade_busca_idfinalidade_busca` INT NOT NULL,
  PRIMARY KEY (`id_situaçao_imovel`, `tipo_imovel_id_tipo_imovel`, `tipo_imovel_contrutora_id_contrutora`, `tipo_imovel_finalidade_busca_idfinalidade_busca`),
  INDEX `fk_situaçao_imovel_tipo_imovel1_idx` (`tipo_imovel_id_tipo_imovel` ASC, `tipo_imovel_contrutora_id_contrutora` ASC, `tipo_imovel_finalidade_busca_idfinalidade_busca` ASC) VISIBLE,
  CONSTRAINT `fk_situaçao_imovel_tipo_imovel1`
    FOREIGN KEY (`tipo_imovel_id_tipo_imovel` , `tipo_imovel_contrutora_id_contrutora` , `tipo_imovel_finalidade_busca_idfinalidade_busca`)
    REFERENCES `bd_imobiliaria`.`tipo_imovel` (`id_tipo_imovel` , `contrutora_id_contrutora` , `finalidade_busca_idfinalidade_busca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`origem_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`origem_contato` (
  `id_origem_contato` INT NOT NULL AUTO_INCREMENT,
  `origem` VARCHAR(45) NULL,
  PRIMARY KEY (`id_origem_contato`))
ENGINE = InnoDB
COMMENT = 'de onde surgiu o contato, stand,indicação.....';


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`identifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`identifica` (
  `id_identifica` INT NOT NULL AUTO_INCREMENT,
  `rg` VARCHAR(45) NOT NULL,
  `creci` VARCHAR(45) NULL,
  `dat_nasc` VARCHAR(45) NOT NULL,
  `cpf_cnpj` VARCHAR(45) NOT NULL,
  `insc_munic` VARCHAR(45) NULL,
  PRIMARY KEY (`id_identifica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`imobiliaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`imobiliaria` (
  `idimobiliaria` INT NOT NULL AUTO_INCREMENT,
  `imobiliaria` VARCHAR(45) NOT NULL,
  `proprietario` VARCHAR(45) NOT NULL,
  `pessoa_id_pessoa` INT NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `endereco_tipo_endereco_id_tipo_endereco` INT NOT NULL,
  `identifica_id_identifica` INT NOT NULL,
  `contato_id contato` INT NOT NULL,
  PRIMARY KEY (`idimobiliaria`, `pessoa_id_pessoa`, `endereco_id_endereco`, `endereco_tipo_endereco_id_tipo_endereco`, `identifica_id_identifica`, `contato_id contato`),
  INDEX `fk_imobiliaria_pessoa1_idx` (`pessoa_id_pessoa` ASC) VISIBLE,
  INDEX `fk_imobiliaria_endereco1_idx` (`endereco_id_endereco` ASC, `endereco_tipo_endereco_id_tipo_endereco` ASC) VISIBLE,
  INDEX `fk_imobiliaria_identifica1_idx` (`identifica_id_identifica` ASC) VISIBLE,
  INDEX `fk_imobiliaria_contato1_idx` (`contato_id contato` ASC) VISIBLE,
  CONSTRAINT `fk_imobiliaria_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `bd_imobiliaria`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imobiliaria_endereco1`
    FOREIGN KEY (`endereco_id_endereco` , `endereco_tipo_endereco_id_tipo_endereco`)
    REFERENCES `bd_imobiliaria`.`endereco` (`id_endereco` , `tipo_endereco_id_tipo_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imobiliaria_identifica1`
    FOREIGN KEY (`identifica_id_identifica`)
    REFERENCES `bd_imobiliaria`.`identifica` (`id_identifica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imobiliaria_contato1`
    FOREIGN KEY (`contato_id contato`)
    REFERENCES `bd_imobiliaria`.`contato` (`id contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`carac_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`carac_imovel` (
  `id_carac_imovel` INT NOT NULL AUTO_INCREMENT,
  `desc_carac_imovel` TINYINT(1) NOT NULL,
  `tipo_imovel_id_tipo_imovel` INT NOT NULL,
  `tipo_imovel_contrutora_id_contrutora` INT NOT NULL,
  PRIMARY KEY (`id_carac_imovel`, `tipo_imovel_id_tipo_imovel`, `tipo_imovel_contrutora_id_contrutora`),
  INDEX `fk_carac_imovel_tipo_imovel1_idx` (`tipo_imovel_id_tipo_imovel` ASC, `tipo_imovel_contrutora_id_contrutora` ASC) VISIBLE,
  CONSTRAINT `fk_carac_imovel_tipo_imovel1`
    FOREIGN KEY (`tipo_imovel_id_tipo_imovel` , `tipo_imovel_contrutora_id_contrutora`)
    REFERENCES `bd_imobiliaria`.`tipo_imovel` (`id_tipo_imovel` , `contrutora_id_contrutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`acab_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`acab_imovel` (
  `id_acab_imovel` INT NOT NULL AUTO_INCREMENT,
  `desc_acab_imovel` VARCHAR(45) NOT NULL,
  `tipo_imovel_id_tipo_imovel` INT NOT NULL,
  `tipo_imovel_contrutora_id_contrutora` INT NOT NULL,
  PRIMARY KEY (`id_acab_imovel`, `tipo_imovel_id_tipo_imovel`, `tipo_imovel_contrutora_id_contrutora`),
  INDEX `fk_acab_imovel_tipo_imovel1_idx` (`tipo_imovel_id_tipo_imovel` ASC, `tipo_imovel_contrutora_id_contrutora` ASC) VISIBLE,
  CONSTRAINT `fk_acab_imovel_tipo_imovel1`
    FOREIGN KEY (`tipo_imovel_id_tipo_imovel` , `tipo_imovel_contrutora_id_contrutora`)
    REFERENCES `bd_imobiliaria`.`tipo_imovel` (`id_tipo_imovel` , `contrutora_id_contrutora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`contato_has_origem_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`contato_has_origem_contato` (
  `contato_id contato` INT NOT NULL AUTO_INCREMENT,
  `origem_contato_id_origem_contato` INT NOT NULL,
  `tipo_contato` VARCHAR(45) NULL,
  `tipo_fone` VARCHAR(45) NULL,
  `nome_recado` VARCHAR(45) NULL,
  PRIMARY KEY (`contato_id contato`, `origem_contato_id_origem_contato`),
  INDEX `fk_contato_has_origem_contato_origem_contato1_idx` (`origem_contato_id_origem_contato` ASC) VISIBLE,
  INDEX `fk_contato_has_origem_contato_contato1_idx` (`contato_id contato` ASC) VISIBLE,
  CONSTRAINT `fk_contato_has_origem_contato_contato1`
    FOREIGN KEY (`contato_id contato`)
    REFERENCES `bd_imobiliaria`.`contato` (`id contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contato_has_origem_contato_origem_contato1`
    FOREIGN KEY (`origem_contato_id_origem_contato`)
    REFERENCES `bd_imobiliaria`.`origem_contato` (`id_origem_contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`Bairro` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` CHAR(10) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Municipio_Id` INT NOT NULL,
  `Municipio_Estado_Id` INT NOT NULL,
  `Municipio_Estado_Regiao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Municipio_Id`, `Municipio_Estado_Id`, `Municipio_Estado_Regiao_Id`),
  INDEX `fk_Bairro_Municipio1_idx` (`Municipio_Id` ASC, `Municipio_Estado_Id` ASC, `Municipio_Estado_Regiao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Municipio1`
    FOREIGN KEY (`Municipio_Id` , `Municipio_Estado_Id` , `Municipio_Estado_Regiao_Id`)
    REFERENCES `bd_imobiliaria`.`Municipio` (`Id` , `Estado_Id` , `Estado_Regiao_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`perm_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`perm_system` (
  `id_perm_system` INT NOT NULL AUTO_INCREMENT,
  `leitura` TINYINT(2) NOT NULL,
  `escrita` TINYINT(2) NOT NULL,
  `gravacao` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id_perm_system`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`acesso_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`acesso_tipo` (
  `id_acesso_tipo` INT NOT NULL AUTO_INCREMENT,
  `acesso` VARCHAR(45) NULL,
  `perm_system_id_perm_system` INT NOT NULL,
  PRIMARY KEY (`id_acesso_tipo`, `perm_system_id_perm_system`),
  INDEX `fk_acesso_tipo_perm_system1_idx` (`perm_system_id_perm_system` ASC) VISIBLE,
  CONSTRAINT `fk_acesso_tipo_perm_system1`
    FOREIGN KEY (`perm_system_id_perm_system`)
    REFERENCES `bd_imobiliaria`.`perm_system` (`id_perm_system`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`acessos` (
  `id_acessos` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `acesso_tipo_id_acesso_tipo` INT NOT NULL,
  `acesso_tipo_perm_system_id_perm_system` INT NOT NULL,
  `contato_id contato` INT NOT NULL,
  PRIMARY KEY (`id_acessos`, `acesso_tipo_id_acesso_tipo`, `acesso_tipo_perm_system_id_perm_system`, `contato_id contato`),
  INDEX `fk_acessos_acesso_tipo1_idx` (`acesso_tipo_id_acesso_tipo` ASC, `acesso_tipo_perm_system_id_perm_system` ASC) VISIBLE,
  INDEX `fk_acessos_contato1_idx` (`contato_id contato` ASC) VISIBLE,
  CONSTRAINT `fk_acessos_acesso_tipo1`
    FOREIGN KEY (`acesso_tipo_id_acesso_tipo` , `acesso_tipo_perm_system_id_perm_system`)
    REFERENCES `bd_imobiliaria`.`acesso_tipo` (`id_acesso_tipo` , `perm_system_id_perm_system`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessos_contato1`
    FOREIGN KEY (`contato_id contato`)
    REFERENCES `bd_imobiliaria`.`contato` (`id contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`pessoa_has_identifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`pessoa_has_identifica` (
  `pessoa_id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `pessoa_profissoes_id_prof` INT(22) NOT NULL,
  `identifica_id_identifica` INT NOT NULL,
  `tipo_pessoa` VARCHAR(45) NOT NULL,
  `est_civil` VARCHAR(45) NOT NULL,
  `conjuge` VARCHAR(45) NULL,
  PRIMARY KEY (`pessoa_id_pessoa`, `pessoa_profissoes_id_prof`, `identifica_id_identifica`),
  INDEX `fk_pessoa_has_identifica_identifica1_idx` (`identifica_id_identifica` ASC) VISIBLE,
  INDEX `fk_pessoa_has_identifica_pessoa1_idx` (`pessoa_id_pessoa` ASC, `pessoa_profissoes_id_prof` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_identifica_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa` , `pessoa_profissoes_id_prof`)
    REFERENCES `bd_imobiliaria`.`pessoa` (`id_pessoa` , `profissoes_id_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_identifica_identifica1`
    FOREIGN KEY (`identifica_id_identifica`)
    REFERENCES `bd_imobiliaria`.`identifica` (`id_identifica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_imobiliaria`.`localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_imobiliaria`.`localizacao` (
  `id_localizaca` INT NOT NULL AUTO_INCREMENT,
  `topografia` VARCHAR(45) NOT NULL,
  `posicao` VARCHAR(45) NOT NULL,
  `orien_solar` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NULL,
  `logintude` VARCHAR(45) NULL,
  `tipo_imovel_id_tipo_imovel` INT NOT NULL,
  `tipo_imovel_contrutora_id_contrutora` INT NOT NULL,
  `tipo_imovel_finalidade_busca_idfinalidade_busca` INT NOT NULL,
  PRIMARY KEY (`id_localizaca`, `tipo_imovel_id_tipo_imovel`, `tipo_imovel_contrutora_id_contrutora`, `tipo_imovel_finalidade_busca_idfinalidade_busca`),
  INDEX `fk_localizacao_tipo_imovel1_idx` (`tipo_imovel_id_tipo_imovel` ASC, `tipo_imovel_contrutora_id_contrutora` ASC, `tipo_imovel_finalidade_busca_idfinalidade_busca` ASC) VISIBLE,
  CONSTRAINT `fk_localizacao_tipo_imovel1`
    FOREIGN KEY (`tipo_imovel_id_tipo_imovel` , `tipo_imovel_contrutora_id_contrutora` , `tipo_imovel_finalidade_busca_idfinalidade_busca`)
    REFERENCES `bd_imobiliaria`.`tipo_imovel` (`id_tipo_imovel` , `contrutora_id_contrutora` , `finalidade_busca_idfinalidade_busca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'concentra informações de localização da área ou imóvel, casa, sala comercial';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
