name: DB CI

on:
  push:
  pull_request:

jobs:
  mysql-ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bd_imobiliaria
          TZ: UTC
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            if mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1" >/dev/null 2>&1; then
              echo "MySQL is up"
              break
            fi
            echo "Waiting MySQL..."
            sleep 2
          done

      - name: Apply schema + seed + indexes
        run: |
          mysql -h 127.0.0.1 -uroot -proot bd_imobiliaria < sql/init/01_schema.sql
          mysql -h 127.0.0.1 -uroot -proot bd_imobiliaria < sql/init/02_seed_minimo.sql
          mysql -h 127.0.0.1 -uroot -proot bd_imobiliaria < sql/init/03_indexes.sql

      - name: Smoke tests
        run: |
          # use SEMPRE o nome em minúsculo (regiao), exatamente como no schema
          mysql -h 127.0.0.1 -uroot -proot bd_imobiliaria -e "SELECT COUNT(*)>0 AS has_regiao FROM regiao;"
          mysql -h 127.0.0.1 -uroot -proot bd_imobiliaria -e "SHOW TABLES;"
